### ISSUE TITLE
Wrong status/icon displayed on CI jobs

### ISSUE THREAD

**Issue by jd** [sileht/pastamaker#11]
I noticed that rather than showing the `time` icon it shows the `cog` icon for the CI (top-left on this screenshot), meaning the jobs are `started`. But it's wrong, clicking on the link shows that the job is only `created` and all the jobs are in the `created` state.

Not sure if it's a sync issue or a display one.

<img width="931" alt="screen shot 2017-07-27 at 12 34 49" src="https://user-images.githubusercontent.com/2644/28666590-4797ec92-72c8-11e7-8694-f8f5cb7c03ce.png">
<img width="741" alt="screen shot 2017-07-27 at 12 36 04" src="https://user-images.githubusercontent.com/2644/28666589-4797bd6c-72c8-11e7-82aa-ad6f2e7d3486.png">

**Comment by sileht** [comment]
I can't do better, one come from github, the other from travis. the github one doesn't make  any difference between started/created/received, they are translated to "pending".

**Comment by jd** [comment]
What about not using GitHub one's but only Travis?

**Comment by sileht** [comment]
The backend doesn't use the travis API, only the github API for now. But why now.

**Comment by sileht** [comment]
I have wrote code to query travis data on backend side, so I think it's fixed now
